export const HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  REQUEST_ENTITY_TOO_LARGE: 413,
};

export const MAX_LENGTH = {
  ROLE_NAME: 35,
  TASK_CATEGORY_NAME: 50,
  CATEGORY_NAME: 35,
  FUNCTION_NAME: 250,
  TITLE_FEEDBACK: 255,
  PROBLEM_STATUS_NAME: 35,
};

export const DATE_FORMAT = {
  DATE_DAY: "ddd DD",
  DATE_MONTH_YEAR: "dd/mm/yy",
  DATE: "ddd",
  DAY: "DD",
  EN_CA: "en-CA",
};

export const SORT_ORDER = {
  ASC: "ASC",
  DESC: "DESC",
};

export const ROWS_PER_PAGE = [10, 20, 50];

export const Permission = {
  // Users Management
  VIEW_ORGANIZATION_USERS: "VIEW_ORGANIZATION_USERS",
  CREATE_ORGANIZATION_USERS: "CREATE_ORGANIZATION_USERS",
  UPDATE_ORGANIZATION_USERS: "UPDATE_ORGANIZATION_USERS",
  DELETE_ORGANIZATION_USERS: "DELETE_ORGANIZATION_USERS",

  // Projects Management
  VIEW_PROJECT: "VIEW_PROJECT",
  VIEW_PROJECTS: "VIEW_PROJECTS",
  CREATE_PROJECTS: "CREATE_PROJECTS",
  UPDATE_PROJECTS: "UPDATE_PROJECTS",
  DELETE_PROJECTS: "DELETE_PROJECTS",

  // Organization Users Management
  VIEW_PROJECT_USERS: "VIEW_PROJECT_USERS",
  CREATE_PROJECT_USERS: "CREATE_PROJECT_USERS",
  UPDATE_PROJECT_USERS: "UPDATE_PROJECT_USERS",
  DELETE_PROJECT_USERS: "DELETE_PROJECT_USERS",

  // Sprints Management
  VIEW_SPRINTS: "VIEW_SPRINTS",
  CREATE_SPRINTS: "CREATE_SPRINTS",
  UPDATE_SPRINTS: "UPDATE_SPRINTS",
  DELETE_SPRINTS: "DELETE_SPRINTS",
  UPDATE_SPRINT_EFFORTS:"UPDATE_SPRINT_EFFORTS",
  VIEW_SPRINT_EFFORTS: "VIEW_SPRINT_EFFORTS",

  // Burndown Charts
  VIEW_BURNDOWN_CHARTS: "VIEW_BURNDOWN_CHARTS",

  // Product Backlogs
  VIEW_PRODUCT_BACKLOGS: "VIEW_PRODUCT_BACKLOGS",

  // Project Settings
  VIEW_PROJECT_SETTINGS: "VIEW_PROJECT_SETTINGS",
  UPDATE_PROJECT_SETTINGS: "UPDATE_PROJECT_SETTINGS",

  // User Story
  VIEW_USER_STORY: "VIEW_USER_STORY",
  CREATE_USER_STORY: "CREATE_USER_STORY",
  UPDATE_USER_STORY: "UPDATE_USER_STORY",
  DELETE_USER_STORY: "DELETE_USER_STORY",

  // User Story Mapping
  VIEW_USER_STORY_MAPPING: "VIEW_USER_STORY_MAPPING",
  UPDATE_USER_STORY_MAPPING: "UPDATE_USER_STORY_MAPPING",
  CREATE_USM_ACTIVITY: "CREATE_USM_ACTIVITY",
  UPDATE_USM_ACTIVITY: "UPDATE_USM_ACTIVITY",
  DELETE_USM_ACTIVITY: "DELETE_USM_ACTIVITY",
  CREATE_USM_RELEASE: "CREATE_USM_RELEASE",
  UPDATE_USM_RELEASE: "UPDATE_USM_RELEASE",
  DELETE_USM_RELEASE: "DELETE_USM_RELEASE",
  CREATE_USM_ACTIVITY_TASK: "CREATE_USM_ACTIVITY_TASK",
  UPDATE_USM_ACTIVITY_TASK: "UPDATE_USM_ACTIVITY_TASK",
  DELETE_USM_ACTIVITY_TASK: "DELETE_USM_ACTIVITY_TASK",

  // Sprint Statistics
  VIEW_SPRINT_STATISTICS: "VIEW_SPRINT_STATISTICS",

  // Daily Meeting
  VIEW_DAILY_MEETING: "VIEW_DAILY_MEETING",
  UPDATE_DAILY_MEETING: "UPDATE_DAILY_MEETING",

  // Kanban
  VIEW_KANBAN: "VIEW_KANBAN",

  // Bug Management
  VIEW_BUG_MANAGEMENT: "VIEW_BUG_MANAGEMENT",
  CREATE_BUG_MANAGEMENT: "CREATE_BUG_MANAGEMENT",
  UPDATE_BUG_MANAGEMENT: "UPDATE_BUG_MANAGEMENT",
  DELETE_BUG_MANAGEMENT: "DELETE_BUG_MANAGEMENT",

  // Issue Management
  VIEW_ISSUES: "VIEW_ISSUES",
  CREATE_ISSUES: "CREATE_ISSUES",
  UPDATE_ISSUES: "UPDATE_ISSUES",
  DELETE_ISSUES: "DELETE_ISSUES",


  // Organizations
  VIEW_ORGANIZATION: "VIEW_ORGANIZATION",
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
  DELETE_ORGANIZATION: "DELETE_ORGANIZATION",

  // System Admins
  VIEW_SYSTEM_ADMIN: "VIEW_SYSTEM_ADMIN",
  CREATE_SYSTEM_ADMIN: "CREATE_SYSTEM_ADMIN",
  UPDATE_SYSTEM_ADMIN: "UPDATE_SYSTEM_ADMIN",
  DELETE_SYSTEM_ADMIN: "DELETE_SYSTEM_ADMIN",

  // Project Admins Management
  ADD_PROJECT_ADMIN: "ADD_PROJECT_ADMIN",
  REMOVE_PROJECT_ADMIN: "REMOVE_PROJECT_ADMIN",

  // Project Users Manager
  ADD_PROJECT_USERS: "ADD_PROJECT_USERS",
  REMOVE_PROJECT_USERS: "REMOVE_PROJECT_USERS",

  // Platform Admins Management
  VIEW_PLATFORM_ADMINS: "VIEW_PLATFORM_ADMINS",
  CREATE_PLATFORM_ADMINS: "CREATE_PLATFORM_ADMINS",
  UPDATE_PLATFORM_ADMINS: "UPDATE_PLATFORM_ADMINS",
  DELETE_PLATFORM_ADMINS: "DELETE_PLATFORM_ADMINS",

  // Organization Features Management
  VIEW_ORGANIZATION_FEATURES: "VIEW_ORGANIZATION_FEATURES",
  UPDATE_ORGANIZATION_FEATURES: "UPDATE_ORGANIZATION_FEATURES",

  // Feedback Management
  VIEW_FEEDBACK_MANAGEMENT: "VIEW_FEEDBACK_MANAGEMENT",

  // System Errors Management
  VIEW_SYS_ERR_MANAGEMENT: "VIEW_SYS_ERR_MANAGEMENT",

  // Problem Status Management
  VIEW_PROBLEM_STATUS_SETTINGS: "VIEW_PROBLEM_STATUS_SETTINGS",
  CREATE_PROBLEM_STATUS_SETTINGS: "CREATE_PROBLEM_STATUS_SETTINGS",
  UPDATE_PROBLEM_STATUS_SETTINGS: "UPDATE_PROBLEM_STATUS_SETTINGS",
  DELETE_PROBLEM_STATUS_SETTINGS: "DELETE_PROBLEM_STATUS_SETTINGS",

  // Problem Management
  VIEW_PROBLEMS: "VIEW_PROBLEMS",
  CREATE_PROBLEMS: "CREATE_PROBLEMS",
  UPDATE_PROBLEMS: "UPDATE_PROBLEMS",
  DELETE_PROBLEMS: "DELETE_PROBLEMS",

  // AI Management
  VIEW_AI_MANAGEMENT: "VIEW_AI_MANAGEMENT"
};

export const SysFeature = {
  PROJECT_MANAGEMENT: "PROJECT_MANAGEMENT",
  SPRINTS_MANAGEMENT: "SPRINTS_MANAGEMENT",
  PRODUCT_BACKLOGS: "PRODUCT_BACKLOGS_MANAGEMENT",
  PROJECT_SETTINGS: "PROJECT_SETTINGS",
  USER_STORY_MANAGEMENT: "USER_STORY_MANAGEMENT",
  USER_STORY_MAPPING: "USER_STORY_MAPPING",
  SPRINT_STATISTICS: "SPRINT_STATISTICS",
  DAILY_MEETING: "DAILY_MEETING",
  KANBAN: "KANBAN",
  BUG_MANAGEMENT: "BUG_MANAGEMENT",
  ISSUE_MANAGEMENT: "ISSUE_MANAGEMENT",
  CATEGORY_SETTINGS: "CATEGORY_SETTINGS",
  TASK_CATEGORY_SETTINGS: "TASK_CATEGORY_SETTINGS",
  ROLE_SETTINGS: "ROLE_SETTINGS",
  ORGANIZATION_MANAGEMENT: "ORGANIZATION_MANAGEMENT",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  PROJECT_ADMINS: "PROJECT_ADMINS",
  PROJECT_USERS_MANAGEMENT: "PROJECT_USERS_MANAGEMENT",
  SYSTEM_ADMIN_MANAGEMENT: "SYSTEM_ADMIN_MANAGEMENT",
  ORGANIZATION_MANAGERS_MANAGEMENT: "ORGANIZATION_MANAGERS_MANAGEMENT",
  ORGANIZATION_USERS_MANAGEMENT: "ORGANIZATION_USERS_MANAGEMENT",
  SYS_ERR_MANAGEMENT: "SYS_ERR_MANAGEMENT",
  PROBLEM_MANAGEMENT: "PROBLEM_MANAGEMENT",
  PROBLEM_STATUS_SETTINGS: "PROBLEM_STATUS_SETTINGS",
  AI_MANAGEMENT: "AI_MANAGEMENT",
};

export const MethodLogin = {
  SYSTEM: "SYSTEM",
  THIRD_PLATFORM: "THIRD_PLATFORM",
  BOTH: "BOTH",
  FACEBOOK: "FACEBOOK",
  GOOGLE: "GOOGLE",
  LINKEDIN: "LINKEDIN",
  TEAMS: "TEAMS"
};

export const UNIT_MULTIPLIER = {
  MB: 1024 * 1024,
  GB: 1024 * 1024 * 1024,
  TB: 1024 * 1024 * 1024 * 1024,
};