export const BrandConstants = {
    TITLE_SHOP: "EZSHOPPING",
    COMPANY_NAME: "Shoez Shop",
    TITLE_PRODUCTS: "Products",
    TITLE_ABOUT: "About",
    TITLE_NEWS: "News",
    TITLE_CONTACT: "Contact",
    TITLE_LOGIN: "Login",
    TITLE_REGISTER: "Register",
    TITLE_LOGOUT: "Logout",
    TITLE_PROFILE: "Profile",
    TITLE_SETTINGS: "Settings",
    TITLE_HELP: "Help",
};

// Brand Names - không thể dịch
export const BrandNames = {
    NIKE: "Nike",
    ADIDAS: "Adidas",
    NEW_BALANCE: "New Balance",
    ASICS: "Asics",
    SAUCONY: "Saucony",
    TIMBERLAND: "Timberland",
    DR_MARTENS: "Dr. Martens",
    UGG: "UGG",
    SOREL: "Sorel",
    ECCO: "ECCO",
    CONVERSE: "Converse",
    PUMA: "Puma",
    VEJA: "Veja",
};

export const TechnologyNames = {
    ZOOM_X: "ZoomX",
    LIGHTSTRIKE_PRO: "Lightstrike Pro",
    FUELCELL: "FuelCell",
    FLYTEFOAM_BLAST_TURBO: "FlyteFoam Blast Turbo",
    GUIDESOLE: "Guidesole",
    PWRRUN_HG: "PWRRUN HG",
    SPEEDROLL: "SPEEDROLL",
    BOOST: "Boost",
    REACT: "React",
    ENCAP: "ENCAP",
    AIR_MAX: "Air Max",
    CLOUDFOAM: "Cloudfoam",
    TREADLITE: "Treadlite",
    AIR_SOLE: "Air-Sole",
    PRIMAKNIT: "Primeknit",
    L_FOAM: "L-Foam",
    GORE_TEX: "GORE-TEX",
    THINSULATE: "Thinsulate",
    PRIMALOFT: "PrimaLoft",
    ENERGY_RODS: "energy rods",
    CARBON_FIBER_PLATE: "Carbon Fiber Plate",
    ENGINEERED_MESH: "engineered mesh",
};

export const ProductNames = {
    ALPHAFLY_3: "Alphafly 3",
    ADIZERO_PRIME_X_2: "Adizero Prime X 2",
    FUELCELL_SUPERCOMP_ELITE_V4: "FuelCell SuperComp Elite v4",
    METASPEED_SKY: "Metaspeed Sky+",
    ENDORPHIN_PRO_4: "Endorphin Pro 4",
    AIR_FORCE_1: "Air Force 1",
    ULTRABOOST_LIGHT: "Ultraboost Light",
    NB_990V6: "990v6",
    CAMPO_LEATHER: "Campo Leather",
    CHUCK_70: "Chuck 70",
    STAN_SMITH: "Stan Smith",
    NB_574: "574",
    RS_X_ECHO: "RS-X Echo",
    SIX_INCH_PREMIUM_BOOT: "6-Inch Premium Boot",
    WINTER_GRIP: "Winter Grip",
    CLASSIC_ULTRA_MINI: "Classic Ultra Mini",
    CARIBOU_BOOT: "Caribou Boot",
    SOFT_7_WINTER: "Soft 7 Winter",
};


export const TechnicalTerms = {
    MIDSOLE: "midsole",
    OUTSOLE: "outsole",
    UPPER: "upper",
    RACING_SHOES: "racing shoes",
    TRAINING_SHOES: "training shoes",
    ROAD_RUNNING: "Road running",
    TRAIL_RUNNING: "trail running",
    TRACK: "track",
    NEUTRAL: "Neutral",
    OVERPRONATION: "overpronation",
    UNDERPRONATION: "underpronation",
    MARATHON: "Marathon",
    QUALITY_CONTROL: "Quality Control",
    QC: "QC",
};