FROM python:3.11-slim

# Cài các gói hệ thống cần thiết để build psycopg2
RUN apt-get update && apt-get install -y build-essential libpq-dev gcc

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]