version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: DockerFile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - minio
    networks:
      - app-network
    env_file:
      - .env  # Dùng env file để nạp biến
    environment:
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}

  minio:
    image: minio/minio
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
